---
title: "Svensk statistik"
author: "av William Lind"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: journal
    css: styles.css
---


```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(stringr)
library(scales)
library(dplyr)
library(tidyr)
library(DT)
library(png)
library(data.table)
library(magrittr)
library(gridExtra)
library(openxlsx)
library(patchwork)
library(ggthemes)
library(plotly)
library(ggridges)
library(forecast)
library(GGally)
library(cluster)
library(sf)
```



## {data-height=200}

### Om initiativet
*Svensk statistik* är ett initiativ taget av William Lind med det huvudsakliga syftet att visualisera utvecklingen i Sverige utifrån ett antal parametrar. Genom SCB är Sverige ett land som ligger i framkant i att lagra registerdata och föra annan statistik på befolkningsnivå, men denna statistik är inte alltid så enkel att ta till sig. Detta är ett försök att förenkla möjligheten att ta till sig av denna data.


## {data-height=400}

### Områden
Dessa områden finns i nuläget rapporter att fördjupa sig inom:
<br>
<br>
- **Demokrati**: Partisympatier, valresultat och valdeltagande.
<br>
- **Arbete**: Arbetsmiljö, arbetstid sysselsättningsgrad och frånvaro.
<br>
- **Utbildning**: Utbildningsnivåer.
<br>
<br>
För att komma åt en rapport, **klicka nedan!**

##
### Rapporter
<style>
  .big-button {
    font-size: 30px;
    padding: 20px 40px;
  }
</style>


<div style="display: flex; gap: 15px; justify-content: left;">
  <a href="https://lindw3.github.io/svenskstatistik-demokrati/" class="btn btn-primary big-button" role="button">DEMOKRATI</a>
  <a href="https://lindw3.github.io/svenskstatistik-demokrati/" class="btn btn-primary big-button" role="button">ARBETE</a>
  <a href="https://lindw3.github.io/svenskstatistik-demokrati/" class="btn btn-primary big-button" role="button">UTBILDNING</a>
</div>